// apps/frontend/src/components/CandidateCard.tsx
import type {
	Candidate,
	Position,
	SupportedLanguage,
	Party,
} from "@repo/constants";
import { CornerDownLeft } from "lucide-react";
import { useLocale } from "@/lib/utils";
import { getCandidateParty } from "@repo/constants";

interface Props {
	candidate: Candidate;
	position: Position;
	imageSrc?: string;
	party?: Party;
}

const i18n = {
	th: {
		langToggle: "EN",
		candidateFor: "ผู้สมัครตำแหน่ง",
		year: "ชั้นปีที่",
		missionTitle: "นโยบายผู้สมัคร",
		experienceTitle: "ประวัติการทำงานของผู้สมัคร",
	},
	en: {
		langToggle: "TH",
		candidateFor: "Candidate for",
		year: "Year",
		missionTitle: "Candidate Policies",
		experienceTitle: "Candidate's Work History",
	},
} as const;

export default function CandidateCard({
	candidate,
	position,
	imageSrc,
	party,
}: Props) {
	const [lang, setLang] = useLocale();
	const t = i18n[lang];

	const positionName = position?.name[lang] ?? position?.name.th ?? "";
	const studyProgram =
		candidate.study_program[lang] ?? candidate.study_program.th ?? "";
	const mission =
		candidate.personal_mission[lang] ?? candidate.personal_mission.th ?? "";
	const experience =
		candidate.personal_experience[lang] ??
		candidate.personal_experience.th ??
		"";
	const candidateParty = getCandidateParty(candidate, party ? [party] : []);
	const partyColor = candidate.color ?? candidateParty?.color;
	return (
		<>
			<div
				style={{ backgroundColor: partyColor ?? "#6b7280" }}
				className={`w-full pt-12 pb-24 `}
			>
				<div className="w-full max-w-3xl mx-auto px-8 sm:px-12">
					<div className="flex justify-between items-center mb-4 relative z-100">
						<a href="/">
							<CornerDownLeft />
						</a>
						<button
							className="text-xs font-semibold border border-black/30 rounded-lg px-3 py-1 bg-white/40 hover:bg-white/70 transition"
							onClick={() => setLang(lang === "th" ? "en" : "th")}
						>
							{t.langToggle}
						</button>
					</div>
					<div className="flex flex-row items-center w-full pb-2 h-40 relative">
						<div className="flex flex-col max-w-54 ">
							<h1 className="font-bold font-noto text-2xl leading-tight mb-2">
								{candidate?.full_name}
							</h1>
							<div className="font-light font-noto text-darkgray text-xs">
								{t.candidateFor} :
							</div>
							<div className="font-bold font-noto text-darkgray text-sm mb-1">
								{positionName}
							</div>
							<div className="font-light font-noto text-darkgray text-xs">
								{studyProgram} <br /> {t.year} {candidate.study_year}
							</div>
						</div>
						<div className="absolute -right-10 -bottom-10 w-50 mt-0 shrink-0 z-2">
							{imageSrc && (
								<img
									src={imageSrc}
									alt={candidate?.full_name}
									className="w-full -translate-y-2"
									style={{ objectPosition: "top" }}
								/>
							)}
						</div>
					</div>
				</div>
			</div>

			<div className="w-full max-w-3xl mx-auto bg-white rounded-t-[2.5rem] pt-8 pb-8 -mt-24 px-8 sm:px-12 relative z-10">
				{/*{imageSrc && (
					<img
						src={imageSrc}
						alt={candidate.full_name}
						className="w-full rounded-2xl object-cover object-top mb-6"
						style={{ maxHeight: "320px" }}
					/>
				)}*/}
				<h2 className="font-bold font-noto text-lg mb-4">{t.missionTitle}</h2>
				<div className="font-noto text-sm text-black leading-relaxed space-y-4">
					{mission.split("\n").map((line, i) => (
						<p key={i}>{line}</p>
					))}
				</div>

				{experience && (
					<>
						<div className="border-t border-black w-full my-6" />
						<h2 className="font-bold font-noto text-base leading-tight mb-4">
							{t.experienceTitle}
						</h2>
						<div className="space-y-3 text-sm font-noto">
							{experience.split("\n").map((line, i) => (
								<p key={i}>{line}</p>
							))}
						</div>
					</>
				)}
			</div>
		</>
	);
}

// apps/frontend/src/components/CandidateCard.svelte
<script lang="ts">
import {
	parties,
	getCandidateParty,
	type Candidate,
	type SupportedLanguage,
} from "@repo/constants";
import { i18n } from "@/lib/i18n";
import { locale } from "@/lib/utils";

interface Props {
	candidate: Candidate;
	image?: string;
	candidateNumber: number;
}

const { candidate: c, image, candidateNumber }: Props = $props();

const t = $derived(i18n[locale.current]);
const langId = $derived(locale.current);
const party = $derived(getCandidateParty(c, parties));
</script>

<div class="flex h-32 mb-6 gap-1">
  <div
    class="flex flex-col w-1/5 items-center justify-center shadow-lg"
    style="background: {c.color ?? party?.color ?? '#6b7280'};"
  >
    <span class="text-xs font-bold text-white">{t.numberLabel}</span>
    <span class="text-2xl font-bold text-white">{c.candidate_number ?? candidateNumber}</span>
  </div>

  <div class="p-3 w-3/5 bg-white shadow-lg">
    <p class="font-bold text-sm">
      {party ? t.party + (party.name[langId] ?? party.name.th ?? '') : t.independentCandidate}
    </p>
    <p class="font-bold text-sm">{c.full_name}</p>
    <div class="h-2.5"></div>
    <p class="text-gray-600 text-xs">{c.study_program[langId]}</p>
    <p class="text-gray-600 text-xs">{t.yearLabel} {c.study_year}</p>
  </div>
  <img
    src={image}
    alt={c.candidate_id}
    class="object-cover shadow-lg bg-white"
    height={32}
    width={96}
  />
</div>
